### ISSUE TITLE
Default span kind should be server for http server middleware

### ISSUE THREAD

**Issue by beauji1116jbn** [vincentfree/opentelemetry#66]
https://github.com/vincentfree/opentelemetry/blob/9ef37494dd75a3ef040596ef3ca44ce31ab57215/otelmiddleware/tracing.go#L79

Since this is a middleware applied on the server side, it's better to set the default span type as `server`
```golang
                ...
                trace.WithSpanKind(trace.SpanKindServer),
                ...
```

**Comment by vincentfree** [comment]
Hi @beauji1116jbn, thanks again. I'll fix this soon
